version: '3.8'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - '8081:80'
    volumes:
      - ./public:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html


  db:
    image: library/mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleet
      MYSQL_USER: root
    ports:
      - '3307:3306'


    # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - '8082:80'

  sqlite:
    image: nouchka/sqlite3

  redis:
    image: redis


